## static_countries
UPDATE static_countries SET cn_short_hu='Andorra' WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_short_hu='Arab Emírségek' WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_short_hu='Afganisztán' WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_short_hu='Antigua és Barbuda' WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_short_hu='Anguilla' WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_short_hu='Albánia' WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_short_hu='Örményország' WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_short_hu='Holland Antillák' WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_short_hu='Angola' WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_short_hu='Antarktisz' WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_short_hu='Argentína' WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_short_hu='Amerikai Szamoa' WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_short_hu='Ausztria' WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_short_hu='Ausztrália' WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_short_hu='Aruba' WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_short_hu='Azerbajdzsán ' WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_short_hu='Bosznia-Hercegovina' WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_short_hu='Barbados' WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_short_hu='Banglades' WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_short_hu='Belgium' WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_short_hu='Burkina Faso' WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_short_hu='Bulgária' WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_short_hu='Bahrein' WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_short_hu='Burundi' WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_short_hu='Benin' WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_short_hu='Bermuda' WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_short_hu='Brunei' WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_short_hu='Bolívia' WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_short_hu='Brazília' WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_short_hu='Bahama-szigetek' WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_short_hu='Bhután' WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_short_hu='Bouvet-sziget' WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_short_hu='Botswana' WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_short_hu='Fehéroroszország' WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_short_hu='Belize' WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_short_hu='Kanada' WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_short_hu='Kókusz-szigetek' WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_short_hu='Kongó ' WHERE cn_iso_2='CD';
UPDATE static_countries SET cn_short_hu='Közép-afrikai Köztársaság' WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_short_hu='Kongói Demokratikus Köztársaság' WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_short_hu='Svájc' WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_short_hu='Elefántcsontpart' WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_short_hu='Cook-szigetek' WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_short_hu='Chile' WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_short_hu='Kamerun' WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_short_hu='Kína' WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_short_hu='Kolumbia' WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_short_hu='Costa Rica' WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_short_hu='Kuba' WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_short_hu='Kap Verde' WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_short_hu='Karácsony-sziget' WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_short_hu='Ciprus' WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_short_hu='Csehország' WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_short_hu='Németország' WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_short_hu='Dzsibuti' WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_short_hu='Dánia' WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_short_hu='Dominikai Közösség' WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_short_hu='Dominikai Köztársaság' WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_short_hu='Algéria' WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_short_hu='Ecuador' WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_short_hu='Észtország' WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_short_hu='Egyiptom' WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_short_hu='Nyugat Szahara' WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_short_hu='Eritrea' WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_short_hu='Spanyolország' WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_short_hu='Etiópia' WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_short_hu='Finnország' WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_short_hu='Fidzsi-szigetek' WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_short_hu='Falkland-szigetek' WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_short_hu='Mikronézia' WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_short_hu='Feröer-szigetek' WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_short_hu='Franciaország' WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_short_hu='Gabon' WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_short_hu='Egyesült Királyság' WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_short_hu='Grenada' WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_short_hu='Grúzia' WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_short_hu='Francia Guyana' WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_short_hu='Ghána' WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_short_hu='Gibraltár' WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_short_hu='Grönland' WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_short_hu='Gambia' WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_short_hu='Guinea' WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_short_hu='Guadeloupe' WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_short_hu='Egyenlítői-Guinea' WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_short_hu='Görögország' WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_short_hu='Dél-Grúzia és a déli Szendvics-szigetek' WHERE cn_iso_2='GS';
UPDATE static_countries SET cn_short_hu='Guatemala' WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_short_hu='Guam' WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_short_hu='Guinea-Bissau' WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_short_hu='Guyana' WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_short_hu='Hong Kong, Kína' WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_short_hu='Honduras' WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_short_hu='Horvátország' WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_short_hu='Haiti' WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_short_hu='Magyarország' WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_short_hu='Indonézia' WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_short_hu='Írország' WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_short_hu='Izrael' WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_short_hu='India' WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_short_hu='Brit területek az Indiai-óceánban' WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_short_hu='Irak' WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_short_hu='Irán' WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_short_hu='Izland' WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_short_hu='Olaszország' WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_short_hu='Jamaica' WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_short_hu='Jordánia' WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_short_hu='Japán' WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_short_hu='Kenya' WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_short_hu='Kirgizisztán' WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_short_hu='Kambodzsa' WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_short_hu='Kiribati' WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_short_hu='Comore-szigetek' WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_short_hu='Saint Kitts és Nevis' WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_short_hu='Észak-Korea' WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_short_hu='Dél-Korea' WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_short_hu='Kuvait' WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_short_hu='Kajmán-szigetek' WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_short_hu='Kazahsztán' WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_short_hu='Laosz' WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_short_hu='Libanon' WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_short_hu='Saint Lucia' WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_short_hu='Lichtenstein' WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_short_hu='Sri Lanka' WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_short_hu='Libéria' WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_short_hu='Lesotho' WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_short_hu='Litvánia' WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_short_hu='Luxemburg' WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_short_hu='Lettország' WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_short_hu='Líbia' WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_short_hu='Marokkó' WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_short_hu='Monaco' WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_short_hu='Moldova' WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_short_hu='Madagaszkár' WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_short_hu='Marshall-szigetek' WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_short_hu='Macedónia' WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_short_hu='Mali' WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_short_hu='Mianmar' WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_short_hu='Mongólia' WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_short_hu='Makao' WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_short_hu='Észak-Marianas' WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_short_hu='Martinique' WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_short_hu='Mauritánia' WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_short_hu='Montserrat' WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_short_hu='Málta' WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_short_hu='Mauritius' WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_short_hu='Maldív-szigetek' WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_short_hu='Malawi' WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_short_hu='Mexikó' WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_short_hu='Malajzia' WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_short_hu='Mozambik' WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_short_hu='Namíbia' WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_short_hu='Új-Kaledónia' WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_short_hu='Niger' WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_short_hu='Norfolk-szigetek' WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_short_hu='Nigéria' WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_short_hu='Nicaragua' WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_short_hu='Hollandia' WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_short_hu='Norvégia' WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_short_hu='Nepál' WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_short_hu='Nauru' WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_short_hu='Niue' WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_short_hu='Új-Zéland' WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_short_hu='Omán' WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_short_hu='Panama' WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_short_hu='Peru' WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_short_hu='Francia Polinézia' WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_short_hu='Pápua Új-Guinea' WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_short_hu='Fülöp-szigetek' WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_short_hu='Pakisztán' WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_short_hu='Lengyelország' WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_short_hu='Saint Pierre és Miquelon' WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_short_hu='Pitcairn-szigetek' WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_short_hu='Puerto Rico' WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_short_hu='Portugália' WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_short_hu='Palau' WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_short_hu='Paraguay' WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_short_hu='Katar' WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_short_hu='Reunion' WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_short_hu='Románia' WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_short_hu='Oroszország' WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_short_hu='Ruanda' WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_short_hu='Szaúd-Arábia' WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_short_hu='Salamon-szigetek' WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_short_hu='Seychelles-szigetek' WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_short_hu='Szudán' WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_short_hu='Svédország' WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_short_hu='Szingapúr' WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_short_hu='Saint Helena' WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_short_hu='Szlovénia' WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_short_hu='Svalbard és Jan Mayen' WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_short_hu='Szlovákia' WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_short_hu='Sierra Leone' WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_short_hu='San Marino' WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_short_hu='Szenegál' WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_short_hu='Szomália' WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_short_hu='Suriname' WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_short_hu='Sao Tomé és Principé' WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_short_hu='Salvador' WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_short_hu='Szíria' WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_short_hu='Szváziföld' WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_short_hu='Turks és Caicos' WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_short_hu='Csád' WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_short_hu='Francia Dél- és Antarktisz régió' WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_short_hu='Togo' WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_short_hu='Thaiföld' WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_short_hu='Tadzsikisztán' WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_short_hu='Tokelau' WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_short_hu='Türkmenisztán' WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_short_hu='Tunézia' WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_short_hu='Tonga' WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_short_hu='Kelet-Timor' WHERE cn_iso_2='TL';
UPDATE static_countries SET cn_short_hu='Törökország' WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_short_hu='Trinidad és Tobago' WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_short_hu='Tuvalu' WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_short_hu='Tajvan' WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_short_hu='Tanzánia' WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_short_hu='Ukrajna' WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_short_hu='Uganda' WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_short_hu='Amerikai Óceánia' WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_short_hu='Amerikai Egyesült Államok' WHERE cn_iso_2='US';
UPDATE static_countries SET cn_short_hu='Uruguay ' WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_short_hu='Üzbegisztán' WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_short_hu='Vatikán' WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_short_hu='Saint Vincent és Grenadine-szigetek' WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_short_hu='Venezuela' WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_short_hu='Virgin-szigetek (brit)' WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_short_hu='Virgin-szigetek (amerikai)' WHERE cn_iso_2='VI';
UPDATE static_countries SET cn_short_hu='Vietnám' WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_short_hu='Vanuatu' WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_short_hu='Wallis és Futuna-szigetek' WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_short_hu='Szamoa' WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_short_hu='Jemen' WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_short_hu='Mayotte' WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_short_hu='Dél-afrikai Köztársaság' WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_short_hu='Zambia' WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_short_hu='Zimbabwe' WHERE cn_iso_2='ZW';
UPDATE static_countries SET cn_short_hu='Palesztína' WHERE cn_iso_2='PS';
UPDATE static_countries SET cn_short_hu='Szerbia és Montenegró' WHERE cn_iso_2='CS';
UPDATE static_countries SET cn_short_hu='Aland-szigetek' WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_short_hu='Heard-szigetek és McDonald-szigetek' WHERE cn_iso_2='HM';
UPDATE static_countries SET cn_short_hu='Montenegró' WHERE cn_iso_2='ME';
UPDATE static_countries SET cn_short_hu='Szerbia' WHERE cn_iso_2='RS';
UPDATE static_countries SET cn_short_hu='Jersey' WHERE cn_iso_2='JE';
UPDATE static_countries SET cn_short_hu='Guernsey' WHERE cn_iso_2='GG';
UPDATE static_countries SET cn_short_hu='Isle of Man' WHERE cn_iso_2='IM';
UPDATE static_countries SET cn_short_hu='Saint Martin' WHERE cn_iso_2='MF';
UPDATE static_countries SET cn_short_hu='Saint Barthélemy' WHERE cn_iso_2='BL';
UPDATE static_countries SET cn_short_hu='Bonaire, Sint Eustatius és Saba' WHERE cn_iso_2='BQ';
UPDATE static_countries SET cn_short_hu='Curacao' WHERE cn_iso_2='CW';
UPDATE static_countries SET cn_short_hu='Sint Maarten' WHERE cn_iso_2='SX';
UPDATE static_countries SET cn_short_hu='Dél-Szudán' WHERE cn_iso_2='SS';
UPDATE static_countries SET cn_short_hu='Koszovó' WHERE cn_iso_2='K1';